### PR TITLE
Adds to Readme: Projects using Docile / Lexicon

### PR DESCRIPTION
**Pull request by peter1000**

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Thanks for taking the trouble to resubmit this one against Docile rather.

With the blank line between the list items the list is actually rendered as two separate lists &ndash; one of the many subtleties of markdown. Removing the blank line will render the list properly.

Also, do we need the package description as well? I'm not opposed to having descriptions for other packages, but it does seem unnecessary to have them Docile / Lexicon. Just a thought though, I'm happy either way.

**Comment by peter1000** [comment]
I will remove the blank line between the list items.
I think it would be still good to keep the descriptions - if someone just comes here and hasn't seen Lexicon it is still good to have it.

**Comment by MichaelHatherly** [comment]
Sure, sounds reasonable.

**Comment by MichaelHatherly** [comment]
Thanks.

**Pull request merged**
