### PR TITLE
Compat update for String rename

### PR DESCRIPTION
**Pull request by StefanKarpinski**
The tests didn't pass for me but the issues seem unrelated to this change. Hope this is helpful.

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Thanks.

**Comment by yuyichao** [comment]
Many of the changes looks likely breaking. Especially since this package is mainly (I know it's not only) for <= 0.4

**Comment by MichaelHatherly** [comment]
After some minor fixes, 1491a9e0fd8083246a8995e74115f198200cd180, tests are passing on 0.3 and 0.4. The package doesn't really expose much that would be affected by this change I think.

**Comment by MichaelHatherly** [comment]
I'll hold off tagging anything for a little while though so I can be sure nothing actually breaks :)

**Pull request merged**
