### PR TITLE
not to be merged only to run Windows tests

### PR DESCRIPTION
**Pull request by peter1000**
try unicode not to be merged only for the Windows problem

Anyway the MetaSyntax tests need to be re-done once the error checks for
`meta within meta` are in place: !!meta(some text an !!innermeta(Test))
should raise an error
https://github.com/MichaelHatherly/Docile.jl/issues/102#issuecomment-100670793

### CODE REVIEW

**Comment by peter1000** [comment]
Interesting this worked - when you saw that you can close it - don't merge it was just a Windows test run to find out about the unicode problem.

**Comment by MichaelHatherly** [comment]
Thanks for looking into this.

**Comment by peter1000** [comment]
**Yesterday I found out what was the problem** - but the PC was out so I did not want to post anymore.

I think it was this: you used originally [isalpha(c)](http://julia.readthedocs.org/en/latest/stdlib/strings/?highlight=isalpha#Base.isalpha)  

`isalpha(c) ? write(name, c) : break` in method: *tryextract*

isalpha
```
A character is classified as alphabetic if it belongs to the 
Unicode general category Letter, i.e. a character whose 
category code begins with ‘L’.
```

```julia

julia> isalpha("笔者(所以不多说了")
false

```

---

after that I changed it for different reason (allowing underscre in metanames) to `isprint` and finally we have `isgraph`

```
julia> isprint("笔者(所以不多说了")
true


julia> isgraph("笔者(所以不多说了")
true

```

It seems we solved it unknowingly as a side effect ;)

**Comment by MichaelHatherly** [comment]
> It seems we solved it unknowingly as a side effect

Ha, cool!

**Pull request closed without merging**
