### PR TITLE
[WIP] DocTags

### PR DESCRIPTION
**Pull request by tshort**
A first cut at DocTags (#59). A new category :doctag is made. Syntax is:

```julia
"""
This is my doctag doc string.
"""
:DOCTAG
```

I included DocTag entries in with other entries with a gensym'd key. I think it's best to leave them as entries. 

Still to do: 

* Add tests
* Have Lexicon skip `:doctag` categories
* Document

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
If we're to store doctags in the entries field then this approach is fine by me. How would this interact with a module that happens to defined an object named `DOCTAG`?

I'd like to understand the reasoning behind storing them in `Metadata.entries` though?

From what I understand of their use case they are a mechanism to add additional context/commentary to output documentation produced by Lexicon based on source code location.

In contrast, the purpose of `Metadata.entries` is to store a module's documented objects and associated docstrings and should be searchable by a user.

I agree with skipping `:doctag` in Lexicon's `?` since a user might get confused upon finding doctags in the results of a search query. If we're having to skip `Entry`s in `Metadata.entries` then I feel that it's probably a sign that there's a better place to store them.

Don't get me wrong though. I'm all for this to get added, but I'd just like it sit well with the rest of the system. I definitely appreciate the work you've been doing so far.

**Comment by MichaelHatherly** [comment]
AppVeyor appears to have given up with this one. Happens sometimes. So long as Travis passes we can generally not worry about it.

**Comment by tshort** [comment]
I think it's best to keep `DOCTAGs` in with the other entries for a few reasons:

* The doc string for a doctag is an Entry, meaning it needs all the data fields currently stored in an Entry.

* Storing doctags separately in the metadata would complicate both Docile and Lexicon. On the Docile side, we complicate what's in Metadata. We'd need to add an array of Entries for doctags. We'd need more code to push those Entries to the right spot. On the Lexicon side, we'd need to do more work in `filter` and `EachEntry` to add them back in. 

If the user had something called `DOCTAG`, doctags will still work as will adding a doc entry for the user's object:

```julia
"my own"
DOCTAG(x) = 1

"some doctag not associated with the `DOCTAG` function."
:DOCTAG
```

**Comment by MichaelHatherly** [comment]
If I want to add a docstring for a `Function` prior to defining it such as:

```julia
"Docs for the `DOCTAG` function."
:DOCTAG

DOCTAG(x) = 1
DOCTAG(x, y) = 2
```

then an `Entry{:doctag}` is created instead and no documentation is associated with function `DOCTAG`.

It's a rather contrived example, but I'd rather not special case a particular word in this way.

**Comment by MichaelHatherly** [comment]
Syntax that I believe would be free to use, but may take a slightly more elaborate change to make work would be something like:

```julia
@doctag """
some doctag docs...
"""

@doctag file"../docs/doctags/first_doctag.md"
```

`@doctag` could just be a no-op macro that [`processast`](https://github.com/MichaelHatherly/Docile.jl/blob/ba0e1260bbe579997a95034a9a4bea8c89d7d73c/src/builddocs.jl#L32-L61) knows how to handle.

**Comment by MichaelHatherly** [comment]
Let go with your choice of storing these as `Entry` objects; it could always be revisited at a later date if needed. The only change in Lexicon we would need is probably [here](https://github.com/MichaelHatherly/Lexicon.jl/blob/1657e7b5fa87ea1ef3c25d43809771d940ddcdff/src/query.jl#L54-L65). Either a conditional to filter them out, or an additional no-op `push!` method for the `Entry{:doctag}` type.

Regarding naming: "doctag" sounds a little too much like "dogtag" I think. Could we possibly investigate other names for this? `@comment` or `@comments` might be more suitable, though there might be others that fit better. Sorry for the bikeshedding @tshort.

**Comment by tshort** [comment]
I'm good with a different name. I like the idea of using a macro to flag
it. Pick what you'd like. Also, I don't have much time this week for
helping.

**Comment by MichaelHatherly** [comment]
Great, thanks for getting back to me on this.

**Comment by MichaelHatherly** [comment]
Closed by 1661d16c31150878b3cdc0821053020ce96055fd.

**Pull request closed without merging**
