### PR TITLE
Preview for code change

### PR DESCRIPTION
**Pull request by peter1000**
Just a preview: I think something like that would be needed for a start.

### CODE REVIEW

**Comment by peter1000** [comment]
sorry forgot the skip ci again.

Had not much time today so here is just a preview what I plan to add (of course the Dummy Code must be replaced with the real thing.)

**Comment by peter1000** [comment]
superseded by #87

**Comment by MichaelHatherly** [comment]
> I think we both must have 5 or more hours time difference

Seems like it, perhaps more. I'm on GMT+2.

**Comment by peter1000** [comment]
ye I'm on GMT/UTC - 03:00 hour we could work 24/7 with that ;)

**Comment by MichaelHatherly** [comment]
> we could work 24/7 with that ;)

Haha, yeah we could :)

**Comment by peter1000** [comment]
just a code question: 
```
    if ismethod(code) || ismacro(code)
        entry.data[:code] = code
    end
```

do I need to but such normally in parentheses

```
    if (ismethod(code) || ismacro(code))
        entry.data[:code] = code
    end
```

because it says http://docs.julialang.org/en/release-0.3/manual/control-flow/#man-short-circuit-evaluation

The reasoning is that a && b must be false if a is false, regardless of the value of b, and likewise, the value of a || b must be true if a is true, regardless of the value of b. Both && and || associate to the right, but && has higher precedence than || does. 

Updated the PR should be fine I hope

**Comment by MichaelHatherly** [comment]
I generally wrap more complex conditions in parentheses. We in doubt though `dump` or `Meta.show_sexpr` helps with reasoning about the behaviour:

```jl
julia> Meta.show_sexpr(:(if ismethod(code) || ismacro(code)
               entry.data[:code] = code
       end))
(:if, (:||, (:call, :ismethod, :code), (:call, :ismacro, :code)), (:block,
    :( # line 2:),
    (:(=), (:ref, (:., :entry, (:quote, #QuoteNode
            :data
          )), (:quote, #QuoteNode
          :code
        )), :code)
  ))
```

**Pull request closed without merging**
