### PR TITLE
Adds support for nested metamacros

### PR DESCRIPTION
**Pull request by peter1000**
Valid Case for: !!meta within !!meta #114
Adds extract metamacro for !!include #120 

Updated also some relevant docs and added some tests

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
I'll review sometime during the weekend and get back to you on this. (Still not happy with loosing non-nesting though. Might have a solution to that though.)

**Comment by peter1000** [comment]
> (Still not happy with loosing non-nesting though. Might have a solution to that though.)

Give me two hour or so and I think I can quite nicely implement the cases you posted.

[here](https://github.com/MichaelHatherly/Docile.jl/issues/114#issuecomment-101663456)
```julia

function Formats.metamacro(::META"hypothetical", body, mod, obj)
    body = do_some_thing_with_the_unexpanded_form(body, mod, obj)
    body = extractmeta!(body, mod, obj) # Now handle nested `!!`.
    do_something_else(body, mod, obj)
end
```

and [here](https://github.com/MichaelHatherly/Docile.jl/issues/114#issuecomment-101670424)

> Having nesting as default is equivalent to the current pattern. This means nothing can happen prior to the line `body = extractmeta!(body, mod, obj)` if we move to automatically nesting.

```julia
function metamacro(::META"...", body, mod, obj)
    body = extractmeta!(body, mod, obj)
    ...
end

```

**Comment by peter1000** [comment]
OK This is what I meant [here](https://github.com/MichaelHatherly/Docile.jl/issues/114#issuecomment-101667786)  This one still loops but I just wanted to show what I meant here and that one can transform each body before the inner are processed.

**Sandbox.jl**

```julia
module Sandbox

import Docile.Formats: Formats, @META_str
import Docile: Cache

function Formats.metamacro(::META"hypothetical_setget", body, mod, obj)
    body = do_some_thing_with_the_unexpanded_form(body, mod, obj)
    body = Formats.extractmeta!(body, mod, obj) # Now handle nested `!!`.
    body = do_something_else(body, mod, obj)
    key, value = split(body, ':', limit = 2)
    Cache.getmeta(mod, obj)[symbol(key)] = value
end

function do_some_thing_with_the_unexpanded_form(body, mod, obj)
    println("printout:do_some_thing_with_the_unexpanded_form: input body: ", body)
    return lowercase(body)
end

function do_something_else(body, mod, obj)
    println("printout:do_something_else: input body: ", body)
    return replace(body, ",", "(Well Done)")
end


"!!hypothetical_setget(unicode_meta_in_meta:所以不多说了 !!hypothetical_setget(水_inner:Cave , Piștireauâ , Höhle , Jaskyňa))"
change_unexpanded_form = ()

end

```


REPL: commands

```

require("Sandbox.jl")
Docile.Cache.getparsed(Sandbox, :change_unexpanded_form)
Docile.Cache.getmeta(Sandbox, :change_unexpanded_form)
```

And the run in REPL and output:

```julia
julia> require("Sandbox.jl")

julia> Docile.Cache.getparsed(Sandbox, :change_unexpanded_form)
Docile: updating package list…
Docile: caching 'Sandbox'…
 - Sandbox ✓
printout:do_some_thing_with_the_unexpanded_form: input body: unicode_meta_in_meta:所以不多说了 !!hypothetical_setget(水_inner:Cave , Piștireauâ , Höhle , Jaskyňa)
printout:do_some_thing_with_the_unexpanded_form: input body: 水_inner:cave , piștireauâ , höhle , jaskyňa
printout:do_something_else: input body: 水_inner:cave , piștireauâ , höhle , jaskyňa
printout:do_something_else: input body: unicode_meta_in_meta:所以不多说了 cave (Well Done) piștireauâ (Well Done) höhle (Well Done) jaskyňa
"所以不多说了 cave (Well Done) piștireauâ (Well Done) höhle (Well Done) jaskyňa"

julia> Docile.Cache.getmeta(Sandbox, :change_unexpanded_form)
Dict{Symbol,Any} with 5 entries:
  :category             => :global
  :水_inner             => "cave (Well Done) piștireauâ (Well Done) höhle (Well Done) jaskyňa"
  :unicode_meta_in_meta => "所以不多说了 cave (Well Done) piștireauâ (Well Done) höhle (Well Done) jaskyňa"
  :textsource           => (25,"/home/workerm/0__DATA__0/TEST_LEXICON/test_metainmetachange/Sandbox.jl")
  :codesource           => (26,"/home/workerm/0__DATA__0/TEST_LEXICON/test_metainmetachange/Sandbox.jl")

julia> 

```

**Comment by peter1000** [comment]
I'm not sure if that above is what you meant  - it just shows that one could indeed manipulate the `outer !!meta` even if we support loop. So compared to not looping I do not see that we would loose much.

I will try to post later something else I had thought of - not yet sure if it works as I planned.

**Comment by peter1000** [comment]
Ok 2 hours - will just need to rewrite the tests for the changes.

**Comment by peter1000** [comment]
Sorry for the wrong to early send comments which I deleted.

Anyway: this PR does nested `!!meta` see the test for `level6 nesting`

> (Still not happy with loosing non-nesting though. Might have a solution to that though.)

* I do not yet have a satisfying solution to this: looking forward what you are coming up with.

**Comment by peter1000** [comment]
just a thought: if you remember we where talking about maube having a [2 pass](https://github.com/MichaelHatherly/Docile.jl/issues/112#issuecomment-101365766)

would that not make it possible to solve the `!!innermetas` in the first pass and still give the option to do what you want?

**Comment by MichaelHatherly** [comment]
I've push 3a735a7c288d8232d3f39a87ed3d7e3df7b69710, which implements nestable metamacros as default and raw metamacros without nesting as

```jl
function metamacro(::META"a_new_metamacro"raw, body, mod, obj)
    # ...
end
```

Should be satisfactory for both of us I should think. Feel free to add the test cases in this PR to what I've already added.

**Pull request closed without merging**
