### PR TITLE
Make the julia, in julia> , optional for repl directive.

### PR DESCRIPTION
**Pull request by hayd**
AKA I'm very lazy and don't want to write julia everywhere. :)

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Or we could be even lazier and not write ``>`` either. Just take each complete expression as a new prompt line.

Might be nice to support ``?`` and ``;`` modes as well. Doesn't need to be in this PR though.

**Comment by hayd** [comment]
The only reason not to do that is multi-line, which is why I thought you went for `julia>`!

Of course we could do, is multiline if it startswith a space (once reindented).

Ah, is there a way to get complete expressions??

**Comment by MichaelHatherly** [comment]
> The only reason not to do that is multi-line

Multi-line should work fine I think:

```
julia> function expressions(text)
           out = []
           index = 1
           while index < length(text)
               ex, index = parse(text, index)
               push!(out, ex)
           end
           out
       end
expressions (generic function with 1 method)

julia> expressions("""
       a = 1
       b = 2
       function foo(x, y)
           x + y
       end
       foo(a, b)
       """
       )
4-element Array{Any,1}:
 :(a = 1)                                                  
 :(b = 2)                                                  
 :(function foo(x,y) # none, line 2:
        x + y
    end)
 :(foo(a,b))   
```

**Comment by hayd** [comment]
Then let's do that!!!!

**Comment by MichaelHatherly** [comment]
That code is already written in [two](https://github.com/MichaelHatherly/Docile.jl/blob/6beba76a739fc5e81e138fb2c7b8e24d8de95c8f/src/Utilities.jl#L56-L64) [places](https://github.com/MichaelHatherly/Docile.jl/blob/6beba76a739fc5e81e138fb2c7b8e24d8de95c8f/src/Docs/directives.jl#L79-L85) so would probably be good to split it out into a ``Utilities.expressions`` function, or some other name, and use it for those places as well.

**Pull request closed without merging**
