### PR TITLE
Update for the next MkDocs version

### PR DESCRIPTION
**Pull request by peter1000**
[configuration](https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md)

[should be released today
20150526](https://github.com/mkdocs/mkdocs/commit/d2f6364c86d7fabe6b8ef90e5fb6aa677e6917d9)

### CODE REVIEW

**Comment by peter1000** [comment]
BTW: the new MkDocs allows nicer configuration of toc layouts

e.g.: 

```yaml
pages:
- Introduction:     index.md
- Manual:
    - Overview:     manual.md
    - Syntax:       syntax.md
    - Metamacros:   metamacros.md
- API:
    - Docile:               api/Docile.md
    - Docile.Cache:         api/Docile.Cache.md
    - Docile.Collector:     api/Docile.Collector.md
    - Docile.Extensions:    api/Docile.Extensions.md
    - API more nesting:
        - Docile.Formats:       api/Docile.Formats.md
        - Docile.Interface:     api/Docile.Interface.md
        - Docile.Legacy:        api/Docile.Legacy.md
        - one level more nesting:
            - Docile.Runner:        api/Docile.Runner.md
            - Docile.Utilities:     api/Docile.Utilities.md
    - Index:                api/index.md
```

produces: 
screenshot from 2015-05-26 10-14-00

**Comment by MichaelHatherly** [comment]
Has readthedocs switched over to this version? I guess we should only merge this once they have. The output looks good though.

**Comment by peter1000** [comment]
I'm not sure if they switched but I guess not  [here](https://github.com/mkdocs/mkdocs/issues/554)

There also some other quite nice feature planned: collapsable ['Rollup' or 'Expand' function in multi-level ToC](https://github.com/mkdocs/mkdocs/issues/556) 

take a look at the [example](http://pip.readthedocs.org/en/stable/)

**Comment by peter1000** [comment]
Seems this should work now with the last mkdocs 0.13.2: [Bugfix](https://github.com/mkdocs/mkdocs/commit/24c22d7283236cc9c7e02c08179613915ee1c6a5)
``` Fix compatibility issues with ReadTheDocs. (#554)```

But you would have to try it yourself.

**Comment by MichaelHatherly** [comment]
I'll merge later today and see what happens. Thanks for your patience.

**Comment by peter1000** [comment]
> Thanks for your patience.

No problem at all.

**Pull request merged**
